// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// matVecProd
NumericMatrix matVecProd(NumericMatrix m, NumericVector v);
RcppExport SEXP PanelCount_matVecProd(SEXP mSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    __result = Rcpp::wrap(matVecProd(m, v));
    return __result;
END_RCPP
}
// matVecProdSum
NumericMatrix matVecProdSum(NumericMatrix m, NumericVector ext, NumericVector v, NumericVector group);
RcppExport SEXP PanelCount_matVecProdSum(SEXP mSEXP, SEXP extSEXP, SEXP vSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ext(extSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    __result = Rcpp::wrap(matVecProdSum(m, ext, v, group));
    return __result;
END_RCPP
}
// matVecProdSumExt
NumericMatrix matVecProdSumExt(NumericMatrix m, NumericVector ext, NumericVector ext2, NumericVector v, NumericVector group);
RcppExport SEXP PanelCount_matVecProdSumExt(SEXP mSEXP, SEXP extSEXP, SEXP ext2SEXP, SEXP vSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ext(extSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ext2(ext2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    __result = Rcpp::wrap(matVecProdSumExt(m, ext, ext2, v, group));
    return __result;
END_RCPP
}
// groupProd
NumericMatrix groupProd(NumericVector v, NumericVector group);
RcppExport SEXP PanelCount_groupProd(SEXP vSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group(groupSEXP);
    __result = Rcpp::wrap(groupProd(v, group));
    return __result;
END_RCPP
}
